#!/usr/bin/env bash
# displaying numbers from 1 to 100.Also display;
# FizzBuzz, when is multiple of 3 and 5
# Fizz, when is multiple of 3
# Buzz, when is a multiple of 5

for num in {1..100}
do
 if (( num % 3 == 0 && num % 5 == 0 ))
 then
  echo "FizzBuzz"
 elif (( num % 3 == 0 ))
 then
  echo "Fizz"
 elif (( num % 5 == 0 ))
 then
  echo "Buzz"
 else
  echo "$num"
 fi
done
