#!/usr/bin/env bash
# In a list format, the content of the current directory,
# and display only the part of the name after the first dash

list=$(ls)
for i in $list; do
 echo "$i" | cut -d '-' -f2
done
